<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['id' => 1, 'code' => 'AF', 'name' => 'Afganisztán', 'is_eu' => false],
            ['id' => 2, 'code' => 'AL', 'name' => 'Albánia', 'is_eu' => false],
            ['id' => 3, 'code' => 'DZ', 'name' => 'Algéria', 'is_eu' => false],
            ['id' => 4, 'code' => 'AD', 'name' => 'Andorra', 'is_eu' => false],
            ['id' => 5, 'code' => 'AO', 'name' => 'Angola', 'is_eu' => false],
            ['id' => 6, 'code' => 'AG', 'name' => 'Antigua és Barbuda', 'is_eu' => false],
            ['id' => 7, 'code' => 'AZ', 'name' => 'Azerbajdzsán', 'is_eu' => false],
            ['id' => 8, 'code' => 'AR', 'name' => 'Argentína', 'is_eu' => false],
            ['id' => 9, 'code' => 'AU', 'name' => 'Ausztrália', 'is_eu' => false],
            ['id' => 10, 'code' => 'AT', 'name' => 'Ausztria', 'is_eu' => true],
            ['id' => 11, 'code' => 'BS', 'name' => 'Bahama-szigetek', 'is_eu' => false],
            ['id' => 12, 'code' => 'BH', 'name' => 'Bahrein', 'is_eu' => false],
            ['id' => 13, 'code' => 'BD', 'name' => 'Banglades', 'is_eu' => false],
            ['id' => 14, 'code' => 'AM', 'name' => 'Örményország', 'is_eu' => false],
            ['id' => 15, 'code' => 'BB', 'name' => 'Barbados', 'is_eu' => false],
            ['id' => 16, 'code' => 'BE', 'name' => 'Belgium', 'is_eu' => true],
            ['id' => 17, 'code' => 'BT', 'name' => 'Bhután', 'is_eu' => false],
            ['id' => 18, 'code' => 'BO', 'name' => 'Bolívia', 'is_eu' => false],
            ['id' => 19, 'code' => 'BA', 'name' => 'Bosznia-Hercegovina', 'is_eu' => false],
            ['id' => 20, 'code' => 'BW', 'name' => 'Botswana', 'is_eu' => false],
            ['id' => 21, 'code' => 'BR', 'name' => 'Brazília', 'is_eu' => false],
            ['id' => 22, 'code' => 'BZ', 'name' => 'Belize', 'is_eu' => false],
            ['id' => 23, 'code' => 'SB', 'name' => 'Salamon-szigetek', 'is_eu' => false],
            ['id' => 24, 'code' => 'BN', 'name' => 'Brunei', 'is_eu' => false],
            ['id' => 25, 'code' => 'BG', 'name' => 'Bulgária', 'is_eu' => true],
            ['id' => 26, 'code' => 'MM', 'name' => 'Mianmar', 'is_eu' => false],
            ['id' => 27, 'code' => 'BI', 'name' => 'Burundi', 'is_eu' => false],
            ['id' => 28, 'code' => 'BY', 'name' => 'Fehéroroszország', 'is_eu' => false],
            ['id' => 29, 'code' => 'KH', 'name' => 'Kambodzsa', 'is_eu' => false],
            ['id' => 30, 'code' => 'CM', 'name' => 'Kamerun', 'is_eu' => false],
            ['id' => 31, 'code' => 'CA', 'name' => 'Kanada', 'is_eu' => false],
            ['id' => 32, 'code' => 'CV', 'name' => 'Zöld-foki Köztársaság', 'is_eu' => false],
            ['id' => 33, 'code' => 'CF', 'name' => 'Közép-Afrika', 'is_eu' => false],
            ['id' => 34, 'code' => 'LK', 'name' => 'Srí Lanka', 'is_eu' => false],
            ['id' => 35, 'code' => 'TD', 'name' => 'Csád', 'is_eu' => false],
            ['id' => 36, 'code' => 'CL', 'name' => 'Chile', 'is_eu' => false],
            ['id' => 37, 'code' => 'CN', 'name' => 'Kína', 'is_eu' => false],
            ['id' => 38, 'code' => 'CO', 'name' => 'Kolumbia', 'is_eu' => false],
            ['id' => 39, 'code' => 'KM', 'name' => 'Comore-szigetek', 'is_eu' => false],
            ['id' => 40, 'code' => 'CG', 'name' => 'Kongói Köztársaság', 'is_eu' => false],
            ['id' => 41, 'code' => 'CD', 'name' => 'Kongói Demokratikus Köztársaság', 'is_eu' => false],
            ['id' => 42, 'code' => 'CR', 'name' => 'Costa Rica', 'is_eu' => false],
            ['id' => 43, 'code' => 'HR', 'name' => 'Horvátország', 'is_eu' => true],
            ['id' => 44, 'code' => 'CU', 'name' => 'Kuba', 'is_eu' => false],
            ['id' => 45, 'code' => 'CY', 'name' => 'Ciprus', 'is_eu' => true],
            ['id' => 46, 'code' => 'CZ', 'name' => 'Csehország', 'is_eu' => true],
            ['id' => 47, 'code' => 'BJ', 'name' => 'Benin', 'is_eu' => false],
            ['id' => 48, 'code' => 'DK', 'name' => 'Dánia', 'is_eu' => true],
            ['id' => 49, 'code' => 'DM', 'name' => 'Dominikai Közösség', 'is_eu' => false],
            ['id' => 50, 'code' => 'DO', 'name' => 'Dominikai Köztársaság', 'is_eu' => false],
            ['id' => 51, 'code' => 'EC', 'name' => 'Ecuador', 'is_eu' => false],
            ['id' => 52, 'code' => 'SV', 'name' => 'El Salvador', 'is_eu' => false],
            ['id' => 53, 'code' => 'GQ', 'name' => 'Egyenlítői-Guinea', 'is_eu' => false],
            ['id' => 54, 'code' => 'ET', 'name' => 'Etiópia', 'is_eu' => false],
            ['id' => 55, 'code' => 'ER', 'name' => 'Eritrea', 'is_eu' => false],
            ['id' => 56, 'code' => 'EE', 'name' => 'Észtország', 'is_eu' => true],
            ['id' => 57, 'code' => 'FJ', 'name' => 'Fidzsi', 'is_eu' => false],
            ['id' => 58, 'code' => 'FI', 'name' => 'Finnország', 'is_eu' => true],
            ['id' => 59, 'code' => 'FR', 'name' => 'Franciaország', 'is_eu' => true],
            ['id' => 60, 'code' => 'DJ', 'name' => 'Dzsibuti', 'is_eu' => false],
            ['id' => 61, 'code' => 'GA', 'name' => 'Gabon', 'is_eu' => false],
            ['id' => 62, 'code' => 'GE', 'name' => 'Grúzia', 'is_eu' => false],
            ['id' => 63, 'code' => 'GM', 'name' => 'Gambia', 'is_eu' => false],
            ['id' => 64, 'code' => 'DE', 'name' => 'Németország', 'is_eu' => true],
            ['id' => 65, 'code' => 'GH', 'name' => 'Ghána', 'is_eu' => false],
            ['id' => 66, 'code' => 'KI', 'name' => 'Kiribati', 'is_eu' => false],
            ['id' => 67, 'code' => 'GR', 'name' => 'Görögország', 'is_eu' => true],
            ['id' => 68, 'code' => 'GD', 'name' => 'Grenada', 'is_eu' => false],
            ['id' => 69, 'code' => 'GT', 'name' => 'Guatemala', 'is_eu' => false],
            ['id' => 70, 'code' => 'GN', 'name' => 'Guinea', 'is_eu' => false],
            ['id' => 71, 'code' => 'GY', 'name' => 'Guyana', 'is_eu' => false],
            ['id' => 72, 'code' => 'HT', 'name' => 'Haiti', 'is_eu' => false],
            ['id' => 73, 'code' => 'VA', 'name' => 'Vatikán', 'is_eu' => false],
            ['id' => 74, 'code' => 'HN', 'name' => 'Honduras', 'is_eu' => false],
            ['id' => 75, 'code' => 'HU', 'name' => 'Magyarország', 'is_eu' => true],
            ['id' => 76, 'code' => 'IS', 'name' => 'Izland', 'is_eu' => false],
            ['id' => 77, 'code' => 'IN', 'name' => 'India', 'is_eu' => false],
            ['id' => 78, 'code' => 'ID', 'name' => 'Indonézia', 'is_eu' => false],
            ['id' => 79, 'code' => 'IR', 'name' => 'Irán', 'is_eu' => false],
            ['id' => 80, 'code' => 'IQ', 'name' => 'Irak', 'is_eu' => false],
            ['id' => 81, 'code' => 'IE', 'name' => 'Írország', 'is_eu' => true],
            ['id' => 82, 'code' => 'IL', 'name' => 'Izrael', 'is_eu' => false],
            ['id' => 83, 'code' => 'IT', 'name' => 'Olaszország', 'is_eu' => true],
            ['id' => 84, 'code' => 'CI', 'name' => 'Elefántcsontpart', 'is_eu' => false],
            ['id' => 85, 'code' => 'JM', 'name' => 'Jamaica', 'is_eu' => false],
            ['id' => 86, 'code' => 'JP', 'name' => 'Japán', 'is_eu' => false],
            ['id' => 87, 'code' => 'KZ', 'name' => 'Kazahsztán', 'is_eu' => false],
            ['id' => 88, 'code' => 'JO', 'name' => 'Jordánia', 'is_eu' => false],
            ['id' => 89, 'code' => 'KE', 'name' => 'Kenya', 'is_eu' => false],
            ['id' => 90, 'code' => 'KP', 'name' => 'Észak-Korea', 'is_eu' => false],
            ['id' => 91, 'code' => 'KR', 'name' => 'Dél-Korea', 'is_eu' => false],
            ['id' => 92, 'code' => 'KW', 'name' => 'Kuvait', 'is_eu' => false],
            ['id' => 93, 'code' => 'KG', 'name' => 'Kirgizisztán', 'is_eu' => false],
            ['id' => 94, 'code' => 'LA', 'name' => 'Laosz', 'is_eu' => false],
            ['id' => 95, 'code' => 'LB', 'name' => 'Libanon', 'is_eu' => false],
            ['id' => 96, 'code' => 'LS', 'name' => 'Lesotho', 'is_eu' => false],
            ['id' => 97, 'code' => 'LV', 'name' => 'Lettország', 'is_eu' => true],
            ['id' => 98, 'code' => 'LR', 'name' => 'Libéria', 'is_eu' => false],
            ['id' => 99, 'code' => 'LY', 'name' => 'Líbia', 'is_eu' => false],
            ['id' => 100, 'code' => 'LI', 'name' => 'Liechtenstein', 'is_eu' => false],
            ['id' => 101, 'code' => 'LT', 'name' => 'Litvánia', 'is_eu' => true],
            ['id' => 102, 'code' => 'LU', 'name' => 'Luxemburg', 'is_eu' => true],
            ['id' => 103, 'code' => 'MG', 'name' => 'Madagaszkár', 'is_eu' => false],
            ['id' => 104, 'code' => 'MW', 'name' => 'Malawi', 'is_eu' => false],
            ['id' => 105, 'code' => 'MY', 'name' => 'Malajzia', 'is_eu' => false],
            ['id' => 106, 'code' => 'MV', 'name' => 'Maldív-szigetek', 'is_eu' => false],
            ['id' => 107, 'code' => 'ML', 'name' => 'Mali', 'is_eu' => false],
            ['id' => 108, 'code' => 'MT', 'name' => 'Málta', 'is_eu' => true],
            ['id' => 109, 'code' => 'MR', 'name' => 'Mauritánia', 'is_eu' => false],
            ['id' => 110, 'code' => 'MU', 'name' => 'Mauritius', 'is_eu' => false],
            ['id' => 111, 'code' => 'MX', 'name' => 'Mexikó', 'is_eu' => false],
            ['id' => 112, 'code' => 'MC', 'name' => 'Monaco', 'is_eu' => false],
            ['id' => 113, 'code' => 'MN', 'name' => 'Mongólia', 'is_eu' => false],
            ['id' => 114, 'code' => 'MD', 'name' => 'Moldova', 'is_eu' => false],
            ['id' => 115, 'code' => 'ME', 'name' => 'Montenegró', 'is_eu' => false],
            ['id' => 116, 'code' => 'MA', 'name' => 'Marokkó', 'is_eu' => false],
            ['id' => 117, 'code' => 'MZ', 'name' => 'Mozambik', 'is_eu' => false],
            ['id' => 118, 'code' => 'OM', 'name' => 'Omán', 'is_eu' => false],
            ['id' => 119, 'code' => 'NA', 'name' => 'Namíbia', 'is_eu' => false],
            ['id' => 120, 'code' => 'NR', 'name' => 'Nauru', 'is_eu' => false],
            ['id' => 121, 'code' => 'NP', 'name' => 'Nepál', 'is_eu' => false],
            ['id' => 122, 'code' => 'NL', 'name' => 'Hollandia', 'is_eu' => true],
            ['id' => 123, 'code' => 'VU', 'name' => 'Vanuatu', 'is_eu' => false],
            ['id' => 124, 'code' => 'NZ', 'name' => 'Új-Zéland', 'is_eu' => false],
            ['id' => 125, 'code' => 'NI', 'name' => 'Nicaragua', 'is_eu' => false],
            ['id' => 126, 'code' => 'NE', 'name' => 'Niger', 'is_eu' => false],
            ['id' => 127, 'code' => 'NG', 'name' => 'Nigéria', 'is_eu' => false],
            ['id' => 128, 'code' => 'NO', 'name' => 'Norvégia', 'is_eu' => false],
            ['id' => 129, 'code' => 'FM', 'name' => 'Mikronézia', 'is_eu' => false],
            ['id' => 130, 'code' => 'MH', 'name' => 'Marshall-szigetek', 'is_eu' => false],
            ['id' => 131, 'code' => 'PW', 'name' => 'Palau', 'is_eu' => false],
            ['id' => 132, 'code' => 'PK', 'name' => 'Pakisztán', 'is_eu' => false],
            ['id' => 133, 'code' => 'PA', 'name' => 'Panama', 'is_eu' => false],
            ['id' => 134, 'code' => 'PG', 'name' => 'Pápua Új-Guinea', 'is_eu' => false],
            ['id' => 135, 'code' => 'PY', 'name' => 'Paraguay', 'is_eu' => false],
            ['id' => 136, 'code' => 'PE', 'name' => 'Peru', 'is_eu' => false],
            ['id' => 137, 'code' => 'PH', 'name' => 'Fülöp-szigetek', 'is_eu' => false],
            ['id' => 138, 'code' => 'PL', 'name' => 'Lengyelország', 'is_eu' => true],
            ['id' => 139, 'code' => 'PT', 'name' => 'Portugália', 'is_eu' => true],
            ['id' => 140, 'code' => 'GW', 'name' => 'Bissau-Guinea', 'is_eu' => false],
            ['id' => 141, 'code' => 'TL', 'name' => 'Kelet-Timor', 'is_eu' => false],
            ['id' => 142, 'code' => 'QA', 'name' => 'Katar', 'is_eu' => false],
            ['id' => 143, 'code' => 'RO', 'name' => 'Románia', 'is_eu' => true],
            ['id' => 144, 'code' => 'RU', 'name' => 'Oroszország', 'is_eu' => false],
            ['id' => 145, 'code' => 'RW', 'name' => 'Ruanda', 'is_eu' => false],
            ['id' => 146, 'code' => 'KN', 'name' => 'Saint Kitts és Nevis', 'is_eu' => false],
            ['id' => 147, 'code' => 'LC', 'name' => 'Saint Lucia', 'is_eu' => false],
            ['id' => 148, 'code' => 'VC', 'name' => 'Saint Vincent és a Grenadine-szigetek', 'is_eu' => false],
            ['id' => 149, 'code' => 'SM', 'name' => 'San Marino', 'is_eu' => false],
            ['id' => 150, 'code' => 'ST', 'name' => 'Sao Tomé és Príncipe', 'is_eu' => false],
            ['id' => 151, 'code' => 'SA', 'name' => 'Szaúd-Arábia', 'is_eu' => false],
            ['id' => 152, 'code' => 'SN', 'name' => 'Szenegál', 'is_eu' => false],
            ['id' => 153, 'code' => 'RS', 'name' => 'Szerbia', 'is_eu' => false],
            ['id' => 154, 'code' => 'SC', 'name' => 'Seychelle-szigetek', 'is_eu' => false],
            ['id' => 155, 'code' => 'SL', 'name' => 'Sierra Leone', 'is_eu' => false],
            ['id' => 156, 'code' => 'SG', 'name' => 'Szingapúr', 'is_eu' => false],
            ['id' => 157, 'code' => 'SK', 'name' => 'Szlovákia', 'is_eu' => true],
            ['id' => 158, 'code' => 'VN', 'name' => 'Vietnam', 'is_eu' => false],
            ['id' => 159, 'code' => 'SI', 'name' => 'Szlovénia', 'is_eu' => true],
            ['id' => 160, 'code' => 'SO', 'name' => 'Szomália', 'is_eu' => false],
            ['id' => 161, 'code' => 'ZA', 'name' => 'Dél-afrikai Köztársaság', 'is_eu' => false],
            ['id' => 162, 'code' => 'ZW', 'name' => 'Zimbabwe', 'is_eu' => false],
            ['id' => 163, 'code' => 'ES', 'name' => 'Spanyolország', 'is_eu' => true],
            ['id' => 164, 'code' => 'SD', 'name' => 'Szudán', 'is_eu' => false],
            ['id' => 165, 'code' => 'SR', 'name' => 'Suriname', 'is_eu' => false],
            ['id' => 166, 'code' => 'SZ', 'name' => 'Szváziföld', 'is_eu' => false],
            ['id' => 167, 'code' => 'SE', 'name' => 'Svédország', 'is_eu' => true],
            ['id' => 168, 'code' => 'CH', 'name' => 'Svájc', 'is_eu' => false],
            ['id' => 169, 'code' => 'SY', 'name' => 'Szíria', 'is_eu' => false],
            ['id' => 170, 'code' => 'TJ', 'name' => 'Tádzsikisztán', 'is_eu' => false],
            ['id' => 171, 'code' => 'TH', 'name' => 'Thaiföld', 'is_eu' => false],
            ['id' => 172, 'code' => 'TG', 'name' => 'Togo', 'is_eu' => false],
            ['id' => 173, 'code' => 'TO', 'name' => 'Tonga', 'is_eu' => false],
            ['id' => 174, 'code' => 'TT', 'name' => 'Trinidad és Tobago', 'is_eu' => false],
            ['id' => 175, 'code' => 'AE', 'name' => 'Egyesült Arab Emírségek', 'is_eu' => false],
            ['id' => 176, 'code' => 'TN', 'name' => 'Tunézia', 'is_eu' => false],
            ['id' => 177, 'code' => 'TR', 'name' => 'Törökország', 'is_eu' => false],
            ['id' => 178, 'code' => 'TM', 'name' => 'Türkmenisztán', 'is_eu' => false],
            ['id' => 179, 'code' => 'TV', 'name' => 'Tuvalu', 'is_eu' => false],
            ['id' => 180, 'code' => 'UG', 'name' => 'Uganda', 'is_eu' => false],
            ['id' => 181, 'code' => 'UA', 'name' => 'Ukrajna', 'is_eu' => false],
            ['id' => 182, 'code' => 'MK', 'name' => 'Macedónia', 'is_eu' => false],
            ['id' => 183, 'code' => 'EG', 'name' => 'Egyiptom', 'is_eu' => false],
            ['id' => 184, 'code' => 'GB', 'name' => 'Egyesült Királyság', 'is_eu' => false],
            ['id' => 185, 'code' => 'GG', 'name' => 'Guernsey', 'is_eu' => false],
            ['id' => 186, 'code' => 'JE', 'name' => 'Jersey', 'is_eu' => false],
            ['id' => 187, 'code' => 'IM', 'name' => 'Man-sziget', 'is_eu' => false],
            ['id' => 188, 'code' => 'TZ', 'name' => 'Tanzánia', 'is_eu' => false],
            ['id' => 189, 'code' => 'US', 'name' => 'USA', 'is_eu' => false],
            ['id' => 190, 'code' => 'VI', 'name' => 'Virgin-szigetek', 'is_eu' => false],
            ['id' => 191, 'code' => 'BF', 'name' => 'Burkina Faso', 'is_eu' => false],
            ['id' => 192, 'code' => 'UY', 'name' => 'Uruguay', 'is_eu' => false],
            ['id' => 193, 'code' => 'UZ', 'name' => 'Üzbegisztán', 'is_eu' => false],
            ['id' => 194, 'code' => 'VE', 'name' => 'Venezuela', 'is_eu' => false],
            ['id' => 195, 'code' => 'WF', 'name' => 'Wallis és Futuna', 'is_eu' => false],
            ['id' => 196, 'code' => 'WS', 'name' => 'Szamoa', 'is_eu' => false],
            ['id' => 197, 'code' => 'YE', 'name' => 'Jemen', 'is_eu' => false],
            ['id' => 198, 'code' => 'ZM', 'name' => 'Zambia', 'is_eu' => false],
        ]);
    }
}
